### PR TITLE
Verishop

### PR DESCRIPTION
**Pull request by SalmaMansouri**

### CODE REVIEW

**Comment by hamidnahli** [comment]
global.py not require, just remove it.

**Comment by hamidnahli** [comment]
Also the last commit does not have the verishop.py. have deleted it?

**Comment by SalmaMansouri** [comment]
> global.py not require, just remove it.

OK

**Comment by SalmaMansouri** [comment]
> Also the last commit does not have the verishop.py. have deleted it?

No,I will solve this problem

**Pull request closed without merging**
